-- ============================================================================
-- 0013 — the 13 Maa Baglamukhi sub-services
-- ============================================================================
-- The category "Maa Baglamukhi Puja & Havan" held exactly one service ("Maa
-- Baglamukhi Havan"), while the business sells thirteen distinct intents
-- underneath it — court case, shatru stambhan, business growth, santan prapti
-- and so on. This inserts those thirteen as services in that category, which
-- is the only sub-service level the schema has: category -> service. There is
-- no services.parent_id, and adding one would mean a new nesting level in the
-- public routes, the admin editor, the SEO render layer and the AI mappings —
-- far more than "list the sub-services" actually needs.
--
-- Content comes from the research-based sub-service master authored for this
-- catalogue. Two deliberate departures from that document:
--
--   1. Its overviews and several FAQ answers are written to the site owner
--      ("PanditSuggest should explain this as...", "Do not promise..."). Those
--      are editorial instructions, not devotee-facing copy, and the one
--      service already in this category shows what happens when they are
--      pasted through: its live description ends mid-sentence in "On
--      PanditSuggest, benefits should be pres...". They are rewritten here as
--      prose addressed to the devotee, keeping every no-guarantee commitment
--      intact — no promise of a court win, an election, profit, a cure, a
--      marriage, a conception, or the removal of black magic.
--   2. process[].duration is left blank rather than filled with invented
--      per-step timings. The source gives none, and a fabricated "15 min" on a
--      ritual step is exactly the kind of detail a devotee would rely on.
--
-- INSERTED INACTIVE (is_active = FALSE) on purpose. These have no images yet;
-- an admin uploads one per service, checks the copy, and flips each live from
-- the admin panel. Nothing appears on the public site until then.
--
-- Every field written here is one the admin services editor round-trips
-- (repositories/admin/services.repository.js): the JSONB shapes are exactly
-- benefits [{icon,title,detail}], process [{step,title,detail,duration}],
-- samagri_list [{item,qty}] and faqs [{q,a}], so opening one of these in the
-- admin panel and pressing Save cannot silently reshape it.
--
-- content_hi is deliberately NOT written. It is the translator's output
-- (services/hindiContent.service.js), produced on an admin save; a Hindi
-- reader falls back to English per field until then, which is the same
-- behaviour as any newly created service.
--
-- Idempotent: ON CONFLICT (slug) DO NOTHING. Re-running never overwrites an
-- admin's later edits.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- The parent category must exist. Resolved by slug with a fallback to the
-- exact name: the live slug is 'maa-baglamukhi-puja & havan' — a space and an
-- ampersand, produced by whatever created it — and a future tidy-up of that
-- slug should not turn this migration into a NOT NULL violation on
-- services.category_id with no explanation.
-- ----------------------------------------------------------------------------
DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.service_categories
     WHERE slug = 'maa-baglamukhi-puja & havan'
        OR name = 'Maa Baglamukhi Puja & Havan'
  ) THEN
    RAISE EXCEPTION 'Migration 0013: the "Maa Baglamukhi Puja & Havan" service category does not exist — create it before loading its sub-services';
  END IF;
END
$guard$;

WITH cat AS (
  SELECT id FROM public.service_categories
   WHERE slug = 'maa-baglamukhi-puja & havan'
      OR name = 'Maa Baglamukhi Puja & Havan'
   ORDER BY (slug = 'maa-baglamukhi-puja & havan') DESC
   LIMIT 1
),
incoming (name, slug, icon_name, display_order,
          description, short_description, estimated_duration,
          recommended_muhurat, online_note,
          benefits, process, samagri_list, faqs) AS (
  VALUES
  ('Court Case Vijay Puja', 'court-case-vijay-baglamukhi-puja', 'book-open', 10,
   'Court Case Vijay Puja is a purpose-based Maa Baglamukhi ritual. You give a clear legal sankalp — an ongoing court matter, a property dispute, a service matter, family litigation or a false accusation — and the pandit performs Maa Baglamukhi pujan, mantra-japa and havan in your name and gotra. Baglamukhi worship is traditionally associated with stambhan, the stilling of harmful speech, hostile intent and opposition, which is why Nalkheda practitioners have long offered it to devotees under legal pressure. It is offered here as a devotional prayer for protection, confidence and a just outcome — never as a guarantee of winning a case, and never as a replacement for your advocate. Choose this service if you are dealing with an ongoing court case, a property or inheritance dispute, a false allegation, service or employment litigation, a family or matrimonial legal matter, or repeated hearing-related stress.',
   'For devotees facing a court case, property dispute, legal notice, false allegation or prolonged litigation. Performed as a prayer for courage, clarity, protection from hostile speech and a fair resolution.',
   '2-4 hours (standard); longer with mantra-anushthan',
   'Chosen with the officiating pandit based on case urgency, your sankalp and the local Panchang. Tuesday, Thursday/Friday and auspicious Devi tithis are commonly used by practitioners, but there is no single compulsory time.',
   'Live sankalp participation is available. Booked as a Nalkheda service, the physical havan is performed by the pandit at Nalkheda while you join remotely.',
   '[{"icon":"🛡️","title":"Legal-pressure support","detail":"Traditionally sought for inner steadiness and spiritual protection through the length of a case."},{"icon":"🗣️","title":"Speech protection prayer","detail":"Baglamukhi worship is associated with the restraint of harmful or hostile speech."},{"icon":"🔥","title":"Courage and clarity","detail":"The sankalp and mantra process support focus before hearings, meetings and decisions."},{"icon":"🪔","title":"Obstacle pacification","detail":"Devotees pray for a reduction in repeated procedural or opposition-related obstacles."},{"icon":"⚖️","title":"Fair-resolution prayer","detail":"The ritual is offered with the intention of justice and an appropriate resolution."},{"icon":"🧘","title":"Mental peace","detail":"A structured devotional practice to hold on to through a stressful legal phase."}]'::jsonb,
   '[{"step":1,"title":"Case Sankalp & Naam-Gotra","detail":"The pandit records your name, gotra if known, the type of case and the exact prayer intention.","duration":""},{"step":2,"title":"Shuddhi, Ganesh & Guru Pujan","detail":"Purification and opening prayers are performed before the main Baglamukhi ritual.","duration":""},{"step":3,"title":"Maa Baglamukhi Avahan & Pujan","detail":"The Devi is invoked with yellow flowers, turmeric, akshat, dhupa, deepa and naivedya.","duration":""},{"step":4,"title":"Baglamukhi Mantra Jaap","detail":"A declared mantra count is recited for the legal sankalp.","duration":""},{"step":5,"title":"Court Case Havan","detail":"Ahutis are offered into the sacred fire with Baglamukhi mantra and the prescribed samagri.","duration":""},{"step":6,"title":"Purnahuti, Aarti & Sankalp Samarpan","detail":"The ritual closes with the final offering, a prayer for justice, aarti and prasad.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Maa Baglamukhi image/yantra","qty":"1"},{"item":"Kalash, coconut, mango leaves","qty":"1 set"},{"item":"Turmeric / haldi pieces","qty":"as advised"},{"item":"Yellow flowers / marigold","qty":"1-2 garlands + loose flowers"},{"item":"Yellow akshat / rice","qty":"1 bowl"},{"item":"Ghee","qty":"250-500 ml for standard havan"},{"item":"Havan samagri","qty":"1 standard pack"},{"item":"Mango wood / samidha","qty":"as required"},{"item":"Roli, moli, sandal, supari","qty":"1 puja set"},{"item":"Incense, camphor, cotton wicks","qty":"1 set"},{"item":"Case papers/photo","qty":"optional, kept respectfully near the sankalp; never placed in the fire"}]'::jsonb,
   '[{"q":"Does this puja guarantee that I will win my court case?","a":"No. It is a spiritual and devotional ritual. Court outcomes depend on facts, law, evidence and the judicial process."},{"q":"What details are required?","a":"Your name, gotra if known, city, the nature of the case and a simple sankalp. The case number is optional unless the pandit specifically asks for it."},{"q":"Can it be performed without me travelling to Nalkheda?","a":"Yes. The pandit can take your sankalp remotely and you may join through live video where that option is available."},{"q":"Is Lal Mirch Havan compulsory for court cases?","a":"No. Some practitioners use special havan variations, but the exact samagri should be selected by the acharya rather than assumed."},{"q":"How long does it take?","a":"A standard puja-havan is usually around 2-4 hours. A larger mantra-anushthan can take longer."},{"q":"Can I submit my legal papers for the puja?","a":"A copy can be respectfully kept near the sankalp if the priest permits. Original legal documents should never be risked or burned."},{"q":"Should I stop legal consultation after the puja?","a":"No. Continue with a qualified advocate and keep every legal deadline. The puja is complementary spiritual support."}]'::jsonb),

  ('Shatru Stambhan Puja', 'shatru-stambhan-baglamukhi-puja', 'shield-check', 20,
   'Shatru Stambhan is one of the best-known intent-based forms of Baglamukhi worship. Stambhan means to still, restrain or immobilise. In plain terms, this service is for someone who feels continuously disturbed by hostile opposition, malicious speech, intimidation, rivalry or deliberate obstruction. The ritual uses a personalised sankalp, Maa Baglamukhi pujan, mantra-japa and havan. It is performed as protection and pacification: the prayer is that harmful conduct, speech and interference lose their power over you. It is never performed to physically harm, curse or destroy anyone. Choose this service if you face persistent hostile opposition, malicious speech or defamation-like pressure, workplace or business rivalry, repeated interference, fear caused by adversaries, or simply need protection and confidence.',
   'For devotees facing persistent opposition, harmful speech, harassment-like pressure or repeated interference. A prayer to restrain hostile intent and protect the devotee — not to harm another person.',
   '2-4 hours',
   'Pandit-guided. Tuesday, Friday, Ashtami and Baglamukhi-related auspicious periods are commonly preferred, but the exact timing varies by tradition.',
   'Live sankalp participation is possible — the pandit takes your sankalp remotely and you may join the ritual by video.',
   '[{"icon":"🛡️","title":"Opposition pacification","detail":"Traditionally sought to reduce the effect of hostile intent and obstruction."},{"icon":"🗣️","title":"Protection from harmful speech","detail":"Baglamukhi is especially associated with control of destructive speech."},{"icon":"🔥","title":"Inner courage","detail":"Supports steadiness while dealing with confrontation or rivalry."},{"icon":"🧘","title":"Mental composure","detail":"Encourages a calm response instead of reactive behaviour."},{"icon":"🪔","title":"Boundary and protection sankalp","detail":"The ritual focuses on spiritual distance from harmful influence."},{"icon":"🕉️","title":"Devi upasana","detail":"Focused worship of Maa Baglamukhi for strength and protection."}]'::jsonb,
   '[{"step":1,"title":"Concern & Sankalp","detail":"You explain the nature of the opposition, without asking for harm to any person.","duration":""},{"step":2,"title":"Shuddhi & Ganesh Pujan","detail":"Opening purification, Ganesh worship and guru remembrance.","duration":""},{"step":3,"title":"Baglamukhi Avahan","detail":"Maa Baglamukhi is invoked with the yellow upacharas.","duration":""},{"step":4,"title":"Stambhan-oriented Mantra Jaap","detail":"The acharya performs the selected mantra-japa for protection and restraint of hostility.","duration":""},{"step":5,"title":"Shatru Stambhan Havan","detail":"Havan is performed with the prescribed Baglamukhi samagri and mantra ahutis.","duration":""},{"step":6,"title":"Purnahuti & Shanti Prarthana","detail":"The final prayer is directed toward protection, peace and an end to harmful interference.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Haldi / turmeric pieces","qty":"as advised"},{"item":"Yellow mustard / chana dal","qty":"as advised by the pandit"},{"item":"Yellow flowers","qty":"as required"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Samidha / havan wood","qty":"as required"},{"item":"Akshat, roli, moli, sandal","qty":"1 set"},{"item":"Incense, camphor, lamp","qty":"1 set"},{"item":"Naivedya / fruit or yellow sweets","qty":"as required"}]'::jsonb,
   '[{"q":"What does “Stambhan” mean here?","a":"It means the spiritual restraint or stilling of harmful opposition, speech or interference."},{"q":"Is this puja intended to hurt an enemy?","a":"No. It is never performed for physical harm, coercion or revenge — only for protection, peace and the restraint of harmful conduct."},{"q":"Do I need to give the other person''s name?","a":"Some priests may ask for context, but the service can be performed with your own protection sankalp. Avoid sharing unnecessary personal details."},{"q":"Can it be done for workplace rivalry?","a":"Yes. Devotees commonly seek it for professional or business opposition, as a prayer for protection and obstacle pacification."},{"q":"Can I join online?","a":"Yes, where the performing pandit offers live sankalp."},{"q":"How is it different from Shatru Nash Puja?","a":"Stambhan focuses on restraining harmful opposition. Shatru Nash is offered as the removal of the problem''s influence — in both cases, never the destruction of a person."},{"q":"Are results guaranteed?","a":"No. It is a traditional spiritual practice, not a guaranteed practical outcome."}]'::jsonb),

  ('Shatru Nash & Protection Puja', 'shatru-nash-protection-baglamukhi-puja', 'trishul', 30,
   'Nalkheda practitioners commonly use the name Shatru Nashak or Shatru Nash Puja, and the meaning deserves to be stated plainly: the prayer is that the harmful influence — the fear, the harassment, the rivalry, the obstruction — comes to an end. The ritual follows Maa Baglamukhi pujan, mantra-japa, havan and purnahuti. Some lineages use special havan samagri or a longer anushthan depending on the situation, which the assigned pandit will tell you in advance. This service is never offered as a way to destroy an enemy; it is a protection and obstacle-removal sankalp. Choose it if you face severe opposition pressure, fear from adversaries, repeated harassment-like interference, a long-running rivalry, or need protection and peace during and after sustained hostility.',
   'A stronger protection-oriented Baglamukhi puja for devotees severely troubled by opposition, fear or persistent hostile interference. Here “Shatru Nash” means the removal of the harmful influence — never harm to a person.',
   '2-4 hours',
   'Selected by the pandit based on your sankalp and the Panchang. Devi tithis and Tuesday/Friday are commonly used by practitioners.',
   'Live sankalp participation is possible. The pandit performs the physical havan and you join remotely or by sankalp.',
   '[{"icon":"🕊️","title":"Removal of harmful influence","detail":"The prayer is that hostile interference no longer controls your life."},{"icon":"🛡️","title":"Protection","detail":"Traditionally sought for spiritual safeguarding during conflict."},{"icon":"🔥","title":"Fear reduction","detail":"Supports courage and emotional steadiness."},{"icon":"🪔","title":"Obstacle removal","detail":"Focused on ending the repeated blocks created by conflict or rivalry."},{"icon":"🤝","title":"Conflict de-escalation prayer","detail":"The closing sankalp seeks peace and a just end to hostility."},{"icon":"🕉️","title":"Spiritual discipline","detail":"Mantra and havan create a focused devotional practice."}]'::jsonb,
   '[{"step":1,"title":"Protection Sankalp","detail":"The purpose is recorded in non-harmful terms: safety, peace and an end to interference.","duration":""},{"step":2,"title":"Purification & Ganesh Pujan","detail":"The standard opening shuddhi and Ganesh worship.","duration":""},{"step":3,"title":"Maa Baglamukhi Pujan","detail":"Yellow offerings and the Devi upacharas are offered.","duration":""},{"step":4,"title":"Mantra Jaap","detail":"The selected Baglamukhi mantra is recited for protection and obstacle removal.","duration":""},{"step":5,"title":"Shatru Nashak / Protection Havan","detail":"Havan ahutis are made as prescribed by the acharya.","duration":""},{"step":6,"title":"Purnahuti & Shanti Sankalp","detail":"The ritual closes with a prayer for safety, justice and a peaceful resolution.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Haldi","qty":"as advised"},{"item":"Yellow flowers","qty":"as required"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Yellow mustard / gram","qty":"as advised"},{"item":"Akshat / rice","qty":"1 bowl"},{"item":"Incense, camphor, wicks","qty":"1 set"},{"item":"Puja thali basics","qty":"1 set"},{"item":"Naivedya","qty":"as required"}]'::jsonb,
   '[{"q":"Why is it called Shatru Nash?","a":"Traditionally the term refers to ending enemy-related trouble. Here it means the removal of a harmful influence, not the destruction of a person."},{"q":"Is it stronger than Shatru Stambhan?","a":"Practitioners often position it as a stronger or more intensive intent, but the actual ritual depth depends on the acharya and the package you choose."},{"q":"Can it be done if I do not know who is opposing me?","a":"Yes. A general protection and obstacle-removal sankalp can be used."},{"q":"Does it involve black magic?","a":"No. Authentic Baglamukhi worship is performed here as a devotional protective ritual; harmful occult practices are not offered."},{"q":"Can I participate online?","a":"Yes, where live sankalp is offered."},{"q":"How long does it take?","a":"Usually 2-4 hours for a standard puja-havan. An extended anushthan may run over several days."},{"q":"Will it solve a police or legal issue automatically?","a":"No. Please use the appropriate legal and safety channels alongside any spiritual practice."}]'::jsonb),

  ('Political / Rajneeti Vijay Puja', 'rajneeti-vijay-baglamukhi-puja', 'award', 40,
   'Rajneeti Vijay, or Political Success Puja, is a purpose-based Baglamukhi service offered by several Nalkheda practitioners. The sankalp may relate to an election, a leadership responsibility, public criticism, political opposition or an important campaign. The spiritual logic is Baglamukhi''s traditional association with speech, confidence, opposition and stambhan. It is performed as a prayer for clear speech, courage, protection from unfair hostility and success in legitimate public work — never for the manipulation of voters, the coercion of opponents, or a guaranteed election victory. Choose this service if you are running an election campaign, carrying public leadership responsibility, facing political opposition or reputation pressure, preparing an important public speech, or working through a difficult leadership decision.',
   'For candidates, public representatives and people in leadership seeking spiritual strength during elections, public opposition, reputation pressure or difficult political work.',
   '2-4 hours',
   'Pandit-guided. Some Nalkheda practitioners prefer Tuesday, Friday, Baglamukhi Jayanti or a chart-based auspicious muhurat.',
   'Live sankalp participation is possible, so a campaign schedule need not be interrupted to attend in person.',
   '[{"icon":"🔥","title":"Confidence in public life","detail":"Devotees seek courage and steadiness through political pressure."},{"icon":"🗣️","title":"Speech discipline","detail":"Baglamukhi worship is traditionally linked with control of speech and debate."},{"icon":"🛡️","title":"Protection from hostility","detail":"A prayer for protection from unfair opposition and malicious attacks."},{"icon":"🏅","title":"Karya siddhi sankalp","detail":"Performed for the successful completion of legitimate political work."},{"icon":"🪔","title":"Reputation steadiness","detail":"A devotional prayer for dignity and composure in public life."},{"icon":"🧘","title":"Leadership clarity","detail":"Supports a calm and focused mindset before important decisions."}]'::jsonb,
   '[{"step":1,"title":"Political / Leadership Sankalp","detail":"The exact legitimate objective is stated: an election, leadership work, a speech or public service.","duration":""},{"step":2,"title":"Ganesh & Guru Pujan","detail":"Opening prayers and purification.","duration":""},{"step":3,"title":"Baglamukhi Avahan","detail":"Devi worship with the yellow offerings.","duration":""},{"step":4,"title":"Vijaya / Vak Shakti Mantra Jaap","detail":"Mantra-japa for confidence, speech discipline and protection.","duration":""},{"step":5,"title":"Rajneeti Vijay Havan","detail":"Havan ahutis are offered for karya siddhi and protection.","duration":""},{"step":6,"title":"Purnahuti & Aarti","detail":"A closing prayer for ethical success, public welfare and peace.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Yellow flowers","qty":"as required"},{"item":"Turmeric","qty":"as advised"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Akshat / rice","qty":"1 bowl"},{"item":"Yellow sweets / fruits","qty":"as required"},{"item":"Incense, camphor, lamp","qty":"1 set"},{"item":"Puja thali basics","qty":"1 set"},{"item":"Campaign symbol/photo","qty":"optional, and only for a respectful sankalp — not for burning"}]'::jsonb,
   '[{"q":"Is this only for election candidates?","a":"No. It can also be booked by people in public leadership or political work who want a devotional sankalp for courage and clarity."},{"q":"Does it guarantee election victory?","a":"No. Election outcomes depend on voters, law, campaigning and many real-world factors."},{"q":"Can it be performed for a speech or an important meeting?","a":"Yes. The sankalp can focus on clear speech, confidence and protection from hostile pressure."},{"q":"Can it be done online?","a":"Yes, with live sankalp participation."},{"q":"Is a kundli required?","a":"Not always, though some practitioners use birth details to choose the muhurat."},{"q":"Is the puja ever done against an opponent?","a":"No. Control over voters, the silencing of opponents and any coercive intent are outside what is offered here."},{"q":"How long does it take?","a":"Usually 2-4 hours for the standard ritual."}]'::jsonb),

  ('Business Growth Puja', 'business-growth-baglamukhi-puja', 'sparkles', 50,
   'Business Growth Puja is widely listed by Nalkheda Baglamukhi practitioners. The ritual is performed with the business or firm name together with the owner''s naam-gotra sankalp. It combines Baglamukhi worship for protection and obstacle pacification with prosperity-oriented prayers, and depending on the pandit''s tradition, Lakshmi or Kuber worship may be included — your package will say exactly what is covered. It suits a devotee looking for spiritual support around slow growth, competitive pressure, blocked payments or a new venture. It is not a guaranteed profit, sales or investment-return service. Choose it if you face slow business growth, competitive pressure, blocked payments, a new venture or expansion, repeated operational obstacles, or the ordinary stress of running a business.',
   'For business owners facing stagnation, competitive pressure, blocked payments, repeated obstacles or uncertainty. Combines Maa Baglamukhi protection with a prosperity-oriented sankalp.',
   '2-3 hours',
   'Friday, an auspicious business-start muhurat, or another date selected by the pandit. The business name and the owner''s sankalp can both be included.',
   'Live sankalp participation is possible, with the firm name and owner details taken remotely before the ritual.',
   '[{"icon":"✨","title":"Business prosperity prayer","detail":"Traditionally sought for auspicious growth and stability."},{"icon":"🛡️","title":"Competitor-pressure protection","detail":"A prayer for protection from unfair rivalry and negative influence."},{"icon":"🧘","title":"Decision clarity","detail":"The sankalp supports calmness and focus in business decisions."},{"icon":"🪔","title":"Obstacle pacification","detail":"Devotees pray for smoother progress in commercial work."},{"icon":"💰","title":"Payment-flow sankalp","detail":"A prayer around delayed receivables can be included, without financial guarantees."},{"icon":"🏺","title":"Positive business beginning","detail":"Suitable before launching, reopening or expanding a venture."}]'::jsonb,
   '[{"step":1,"title":"Business Sankalp","detail":"The business name, owner details and the main concern are recorded.","duration":""},{"step":2,"title":"Ganesh & Kalash Pujan","detail":"Opening worship for auspiciousness.","duration":""},{"step":3,"title":"Baglamukhi & Prosperity Pujan","detail":"Maa Baglamukhi is worshipped; some traditions add Lakshmi or Kuber prayers.","duration":""},{"step":4,"title":"Mantra Jaap","detail":"Baglamukhi and prosperity mantra counts are recited as declared.","duration":""},{"step":5,"title":"Vyapar Vriddhi Havan","detail":"Fire offerings are made with the prescribed yellow and prosperity samagri.","duration":""},{"step":6,"title":"Purnahuti & Business Prarthana","detail":"A closing prayer for ethical growth, stability and wise action.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Lakshmi/Kuber image or Shri Yantra","qty":"optional, by tradition"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow flowers / lotus if available","qty":"as required"},{"item":"Turmeric / yellow mustard","qty":"as advised"},{"item":"Rice / akshat","qty":"1 bowl"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Coins","qty":"symbolic offering, small quantity"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Business card / firm name sheet","qty":"optional, for the sankalp only"}]'::jsonb,
   '[{"q":"Can I book this for a new business?","a":"Yes. It is commonly used as an auspicious beginning and a protection-oriented business sankalp."},{"q":"Can it help with blocked payments?","a":"A blocked-payment concern can be included in the sankalp, but the puja does not guarantee the recovery of money."},{"q":"Is Lakshmi Puja included?","a":"Some Nalkheda practitioners combine Baglamukhi and Lakshmi-oriented worship. Your service package states clearly what is included."},{"q":"Do I need my company documents?","a":"No. The firm or business name and the owner''s details are usually enough for the sankalp."},{"q":"Can partners join together?","a":"Yes. All relevant owners and partners can be included if the pandit permits."},{"q":"Can it be online?","a":"Yes."},{"q":"Should practical business action continue?","a":"Yes. Spiritual worship complements accounting, sales, contracts, legal advice and business planning — it does not replace them."}]'::jsonb),

  ('Lakshmi / Dhan Prapti Puja', 'lakshmi-dhan-prapti-baglamukhi-puja', 'kalash', 60,
   'Dhan Prapti and Lakshmi Prapti services appear in Nalkheda practitioner catalogues as prosperity-oriented Baglamukhi rituals. The exact deity combination and mantra method vary by lineage: some use Maa Baglamukhi with Lakshmi, the Shri Yantra, Kuber or other prosperity mantras, and the assigned pandit will tell you which applies to your booking. It is offered as a prayer for financial stability, responsible prosperity and the removal of perceived spiritual obstacles around money. It does not promise sudden wealth, debt cancellation, lottery success or a guaranteed income. Choose it for a financial stability prayer, repeated money obstacles, business prosperity, a new financial beginning, a household prosperity sankalp, or simply as gratitude and abundance worship.',
   'A prosperity-focused devotional service for financial stability, a dhan-prapti sankalp and relief from repeated money-related obstacles, often combining Maa Baglamukhi with Lakshmi-oriented worship.',
   '2-3 hours',
   'Friday, Diwali-related auspicious periods, or a muhurat selected by the pandit.',
   'Live sankalp participation is possible; the family or business prosperity sankalp is taken in your name remotely.',
   '[{"icon":"🏺","title":"Prosperity prayer","detail":"Devotees seek auspicious financial stability and abundance."},{"icon":"🪔","title":"Money-obstacle pacification","detail":"A devotional sankalp for repeated financial blockages."},{"icon":"🌸","title":"Lakshmi blessings","detail":"Many traditions add Lakshmi-oriented worship for Shri and prosperity."},{"icon":"🙏","title":"Responsible abundance","detail":"The ritual reinforces gratitude and the disciplined use of resources."},{"icon":"🏠","title":"Business or household auspiciousness","detail":"Suitable for a family or business prosperity sankalp."},{"icon":"✨","title":"Positive new beginning","detail":"Often chosen before a venture, a purchase or a financial reset."}]'::jsonb,
   '[{"step":1,"title":"Financial Sankalp","detail":"You state a simple and ethical prosperity intention.","duration":""},{"step":2,"title":"Ganesh & Kalash Pujan","detail":"The opening worship.","duration":""},{"step":3,"title":"Baglamukhi-Lakshmi Pujan","detail":"Maa Baglamukhi and, where included, Lakshmi or the Shri Yantra are worshipped.","duration":""},{"step":4,"title":"Prosperity Mantra Jaap","detail":"The declared mantra count is recited.","duration":""},{"step":5,"title":"Dhan Prapti Havan","detail":"Havan with ghee, grains and the prescribed prosperity and yellow samagri.","duration":""},{"step":6,"title":"Purnahuti & Aarti","detail":"A final prayer for stability, gratitude and ethical prosperity.","duration":""}]'::jsonb,
   '[{"item":"Yellow/red cloth","qty":"1 set"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Lakshmi image / Shri Yantra","qty":"if included"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow and pink/red flowers","qty":"as required"},{"item":"Turmeric, rice, kumkum","qty":"1 set"},{"item":"Coins","qty":"symbolic offering"},{"item":"Lotus seeds / kamal gatta","qty":"optional, by tradition"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Incense, camphor, lamps","qty":"1 set"}]'::jsonb,
   '[{"q":"Is this the same as a standard Lakshmi Puja?","a":"Not always. This service is a Baglamukhi-based prosperity sankalp and may include Lakshmi worship depending on the pandit."},{"q":"Will it make me rich quickly?","a":"No. It is a devotional ritual, not a financial product or a guarantee."},{"q":"Can I book it for debt stress?","a":"You may include financial-pressure concerns, but debt still requires practical repayment planning and professional advice where needed."},{"q":"Is Friday compulsory?","a":"Friday is commonly associated with Lakshmi, but the final muhurat can vary."},{"q":"Can it be performed for the entire family?","a":"Yes. A family prosperity sankalp can be taken."},{"q":"Can it be online?","a":"Yes."},{"q":"Should coins be donated after the puja?","a":"That depends on the priest''s tradition. Follow the pandit''s instructions rather than assuming a fixed rule."}]'::jsonb),

  ('Career & Job Success Puja', 'career-job-success-baglamukhi-puja', 'briefcase', 70,
   'Career and Job Success Puja is offered by Nalkheda practitioners as a Baglamukhi-based karya siddhi service. It is meant for a specific, real concern: repeated interview failure, a promotion delay, workplace politics, job insecurity or career stagnation. The ritual includes Maa Baglamukhi pujan, mantra-japa and havan, and if the pandit recommends it, a supporting graha-shanti element that will be disclosed to you in advance. No puja can guarantee a job or a promotion — your skills, preparation, applications and professional decisions remain essential, and this is offered alongside them, not instead of them. Choose it if you are facing a job-search delay, interview nerves, a promotion or appraisal concern, workplace opposition, career stagnation, or job insecurity and transition.',
   'For job delay, interview pressure, promotion concerns, workplace opposition or career instability. A prayer for confidence, clarity, opportunity and the removal of obstacles.',
   '2-3 hours',
   'Selected by the pandit, and often timed before an interview, a joining date, an appraisal or another auspicious day.',
   'Live sankalp participation is possible, so the ritual can be timed around an interview or joining date.',
   '[{"icon":"🪔","title":"Career obstacle prayer","detail":"Traditionally sought for smoother professional progress."},{"icon":"🗣️","title":"Interview confidence","detail":"Supports mental steadiness and speech discipline."},{"icon":"🛡️","title":"Workplace protection","detail":"A prayer for protection from unfair rivalry or hostility."},{"icon":"🧘","title":"Decision clarity","detail":"A devotional process for calm career choices."},{"icon":"💼","title":"Opportunity sankalp","detail":"You can pray for suitable work opportunities."},{"icon":"🔥","title":"Motivation and discipline","detail":"The structure of the ritual reinforces focus alongside practical effort."}]'::jsonb,
   '[{"step":1,"title":"Career Sankalp","detail":"You state the job or career concern — an interview, a promotion or workplace pressure.","duration":""},{"step":2,"title":"Ganesh & Guru Pujan","detail":"Opening purification and blessings.","duration":""},{"step":3,"title":"Baglamukhi Pujan","detail":"Devi worship with the yellow offerings.","duration":""},{"step":4,"title":"Career / Karya Siddhi Mantra Jaap","detail":"The selected Baglamukhi mantra count is recited.","duration":""},{"step":5,"title":"Job & Career Havan","detail":"Ahutis are offered for obstacle removal and confidence.","duration":""},{"step":6,"title":"Purnahuti & Aarti","detail":"A closing prayer for the right opportunity and wise action.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow flowers","qty":"as required"},{"item":"Turmeric / yellow mustard","qty":"as advised"},{"item":"Akshat / rice","qty":"1 bowl"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Incense, camphor, lamp","qty":"1 set"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Puja thali basics","qty":"1 set"},{"item":"Resume / offer letter copy","qty":"optional, for the sankalp only"}]'::jsonb,
   '[{"q":"Can this puja guarantee a new job?","a":"No. It is spiritual support. Job outcomes depend on skills, applications, market conditions and interviews."},{"q":"Can I book it before an interview?","a":"Yes. The sankalp can be specifically for confidence, clear speech and a suitable outcome."},{"q":"Is it useful for promotion concerns?","a":"That is a common reason devotees book a career-oriented puja, but a promotion is never guaranteed."},{"q":"Can a student book it for campus placement?","a":"Yes. The sankalp can be adapted for a placement or first-job concern."},{"q":"Can it be online?","a":"Yes."},{"q":"Is a kundli review necessary?","a":"Not for a general devotional service. It may be added if a graha-specific remedy is being recommended."},{"q":"What else should I do?","a":"Continue with interview preparation, networking, applications and professional guidance alongside the puja."}]'::jsonb),

  ('Rog Nashak Puja', 'rog-nashak-baglamukhi-puja', 'sun', 80,
   'Rog Nashak services are offered by Nalkheda Baglamukhi practitioners, sometimes combining Pitambara/Baglamukhi worship with Maha Mrityunjaya or other health prayers. The puja is performed for spiritual strength, peace, courage and wellbeing during illness or recovery. It does not cure disease, replace a doctor, justify stopping any medicine, or guarantee recovery — please continue with the treatment your clinician has advised. The exact mantra and deity combination is disclosed by the assigned pandit before the booking is confirmed. Choose this service for a prayer during illness, a post-treatment or recovery phase, a family member''s health sankalp, mental strength during medical stress, a general wellbeing prayer, or health-related fear and uncertainty.',
   'A health and wellbeing prayer for devotees or family members going through illness, recovery, stress or a difficult health phase. Spiritual support only — it does not replace medical care.',
   '2-3 hours',
   'Selected by the pandit. An urgent health prayer need not wait for a distant festival — the priest can choose a suitable available muhurat.',
   'Can be performed in the patient''s name even if they are unable to attend, with the family joining by live sankalp.',
   '[{"icon":"🙏","title":"Wellbeing prayer","detail":"A devotional sankalp for health, strength and recovery."},{"icon":"🧘","title":"Mental peace","detail":"Supports calmness through a stressful health period."},{"icon":"👨‍👩‍👧","title":"Family spiritual support","detail":"Relatives can offer the ritual in the patient''s name."},{"icon":"🔥","title":"Courage","detail":"Mantra and prayer can provide emotional steadiness."},{"icon":"🛡️","title":"Protective devotion","detail":"Maa Baglamukhi is invoked for spiritual protection."},{"icon":"🕉️","title":"Optional Shiva prayer","detail":"Some practitioners combine Maha Mrityunjaya or Shiva-related prayers; your package states this clearly."}]'::jsonb,
   '[{"step":1,"title":"Health Sankalp","detail":"The patient''s name, gotra if known, and a simple wellbeing intention are recorded.","duration":""},{"step":2,"title":"Ganesh & Shuddhi Pujan","detail":"Opening purification and Ganesh worship.","duration":""},{"step":3,"title":"Baglamukhi / Health Deity Pujan","detail":"Maa Baglamukhi is worshipped; any additional Shiva or Mrityunjaya element is stated in advance.","duration":""},{"step":4,"title":"Mantra Jaap","detail":"The declared health-prayer mantra count is recited.","duration":""},{"step":5,"title":"Rog Nashak Havan","detail":"Havan is performed with the standard approved samagri.","duration":""},{"step":6,"title":"Purnahuti & Shanti Path","detail":"A closing peace prayer, followed by prasad.","duration":""}]'::jsonb,
   '[{"item":"Yellow/white cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Shiva image/lingam","qty":"only if the package includes the Mrityunjaya element"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow/white flowers","qty":"as required"},{"item":"Bilva leaves","qty":"only if Shiva puja is included"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Akshat, turmeric, sandal","qty":"1 set"},{"item":"Incense, camphor, lamps","qty":"1 set"},{"item":"Fruits / satvik naivedya","qty":"as required"},{"item":"Patient photo/name sheet","qty":"optional, for the sankalp"}]'::jsonb,
   '[{"q":"Can this puja cure an illness?","a":"No. It is a spiritual prayer and must not replace medical diagnosis or treatment."},{"q":"Can it be performed for someone in hospital?","a":"Yes. The sankalp can be taken in that person''s name while they continue their medical care."},{"q":"Should medicines be stopped for the puja?","a":"No. Never stop prescribed treatment unless the treating clinician advises it."},{"q":"Is Maha Mrityunjaya included?","a":"Some practitioners include it and some do not. Your package states the actual mantra and deity combination."},{"q":"Can family members join online?","a":"Yes."},{"q":"How long does it take?","a":"Usually 2-3 hours for a standard puja-havan."},{"q":"What does the puja actually offer?","a":"Health and wellbeing prayer, spiritual support and mental strength during a difficult phase — never a cure or a guaranteed result."}]'::jsonb),

  ('Vivah Badha Nivaran Puja', 'vivah-badha-nivaran-baglamukhi-puja', 'rings', 90,
   'Vivah Badha Nivaran Puja is repeatedly listed by Nalkheda practitioners, though the exact format differs between them: some combine Baglamukhi worship with Mangal Shanti, Rahu-Ketu remedies or Swayamvar Parvati prayers. Your package will show clearly which of these are actually included, so nothing is assumed. The core intent is straightforward — repeated delay or obstacles in the path to marriage — and the ritual is offered as a prayer for a suitable, consensual and auspicious alliance. It never promises a particular person, forces a relationship, or guarantees marriage by a fixed date. Choose it if you face repeated marriage delay, proposal obstacles, family resistance, recurring misunderstandings, an astrology-linked marriage concern, or simply wish to pray for a suitable alliance.',
   'For people facing repeated marriage delay, proposal obstacles, misunderstandings or family resistance. A devotional prayer for suitable progress, clarity and harmony.',
   '2-4 hours; an extended anushthan may take multiple days',
   'Selected by the pandit or astrologer. A chart review may be useful if the service includes Mangal, Rahu-Ketu or other graha remedies.',
   'Live sankalp participation is possible, with the name, gotra and concern taken remotely before the ritual.',
   '[{"icon":"💍","title":"Marriage-obstacle prayer","detail":"Traditionally sought when marriage progress repeatedly stalls."},{"icon":"🧘","title":"Clarity and calm","detail":"Supports emotional steadiness through a stressful matchmaking phase."},{"icon":"🏠","title":"Family harmony sankalp","detail":"A prayer for the reduction of family-related tension can be included."},{"icon":"🌙","title":"Graha-shanti support","detail":"Where recommended, Mangal or Rahu-Ketu remedies may be added."},{"icon":"🤝","title":"Suitable-alliance prayer","detail":"Focused on an appropriate and mutually respectful marriage path."},{"icon":"🕉️","title":"Devi blessings","detail":"Maa Baglamukhi worship for protection and obstacle pacification."}]'::jsonb,
   '[{"step":1,"title":"Marriage Concern Sankalp","detail":"Name, gotra, age and the nature of the delay or obstacle are recorded.","duration":""},{"step":2,"title":"Ganesh & Kalash Pujan","detail":"The opening worship.","duration":""},{"step":3,"title":"Baglamukhi Pujan","detail":"Maa Baglamukhi is invoked with the yellow offerings.","duration":""},{"step":4,"title":"Optional Graha / Parvati Element","detail":"Only if included: Mangal Shanti, Rahu-Ketu or a Swayamvar Parvati-oriented prayer.","duration":""},{"step":5,"title":"Vivah Badha Havan","detail":"Havan ahutis are offered for obstacle removal and harmony.","duration":""},{"step":6,"title":"Purnahuti & Aarti","detail":"A closing prayer for a suitable, consensual and auspicious marriage path.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow/red flowers","qty":"as required"},{"item":"Turmeric / kumkum / akshat","qty":"1 set"},{"item":"Moli / sacred thread","qty":"1"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Incense, camphor, lamps","qty":"1 set"},{"item":"Graha-specific samagri","qty":"only if included"},{"item":"Photo/biodata","qty":"optional, respectfully kept for the sankalp only"}]'::jsonb,
   '[{"q":"Does this puja guarantee marriage within a fixed time?","a":"No. It is a devotional remedy, and no fixed result or timeline is guaranteed."},{"q":"Can it make a specific person marry me?","a":"No. Coercive or non-consensual intentions are not accepted. The sankalp is for a suitable, mutual and auspicious relationship."},{"q":"Is Mangal Dosh Puja always included?","a":"No. It is included only if your package says so, and ideally after a kundli assessment."},{"q":"Can parents book it for their son or daughter?","a":"Yes, depending on the priest''s tradition — but the individual''s consent and dignity must be respected."},{"q":"Can it be online?","a":"Yes."},{"q":"What details are needed?","a":"Name, gotra if known, date of birth if astrology is being used, and a brief description of the concern."},{"q":"Is counselling or matchmaking still useful?","a":"Yes. Spiritual practice complements healthy communication, counselling and practical matchmaking efforts."}]'::jsonb),

  ('Santan Prapti Puja', 'santan-prapti-baglamukhi-puja', 'baby', 100,
   'Santan Prapti Anushthan is offered by several Nalkheda practitioners as a family and progeny-related prayer. The exact ritual may be Baglamukhi-centred, or may include Krishna/Santan Gopal, Shiva-Parvati or Navgraha prayers depending on the acharya, and the assigned pandit states exactly what will be performed. Because this is a medical and emotionally sensitive area, the service makes no promise of conception, offers no treatment for infertility and makes no claim about preventing miscarriage. It is devotional support for hope, family wellbeing and the couple''s shared sankalp. Choose it as a prayer for progeny, a couple''s family sankalp, emotional support during a fertility journey, a family wellbeing prayer, an astrology-guided santan concern, or devotional hope after a long wait.',
   'A devotional family prayer for couples seeking the blessing of children, hope and emotional strength. Spiritual support that does not replace fertility or obstetric care.',
   '2-4 hours; an anushthan format may run longer',
   'Selected by the pandit. If astrology is part of the package, birth details may be reviewed; no universal fixed time applies.',
   'The couple can join live, or the sankalp can be taken in both their names if they cannot attend.',
   '[{"icon":"👶","title":"Progeny prayer","detail":"A traditional devotional sankalp for the blessing of children."},{"icon":"🤝","title":"The couple''s shared worship","detail":"Creates a joint spiritual practice for both partners."},{"icon":"🕊️","title":"Hope and emotional support","detail":"A structured prayer to hold on to through a difficult journey."},{"icon":"🏠","title":"Family wellbeing","detail":"Includes a prayer for a healthy and harmonious family."},{"icon":"🌙","title":"Optional graha support","detail":"Some priests add Navgraha or other remedies where recommended."},{"icon":"🕉️","title":"Devi grace","detail":"Maa Baglamukhi is worshipped for protection and the removal of obstacles."}]'::jsonb,
   '[{"step":1,"title":"Couple Sankalp","detail":"Both partners'' names, gotra and the family prayer are recorded.","duration":""},{"step":2,"title":"Ganesh & Kalash Pujan","detail":"Opening purification and worship.","duration":""},{"step":3,"title":"Baglamukhi / Santan-related Pujan","detail":"The specific deity combination named in your package is worshipped.","duration":""},{"step":4,"title":"Mantra Jaap","detail":"The declared mantra count is recited in the couple''s sankalp.","duration":""},{"step":5,"title":"Santan Prapti Havan","detail":"Havan ahutis are offered as prescribed.","duration":""},{"step":6,"title":"Purnahuti & Family Blessing Prayer","detail":"A closing prayer for wellbeing, patience and family blessings.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Santan Gopal/Krishna image","qty":"only if included"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow/white flowers","qty":"as required"},{"item":"Tulsi","qty":"only if the Krishna element is included"},{"item":"Akshat, turmeric, sandal","qty":"1 set"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Incense, camphor, lamps","qty":"1 set"},{"item":"Couple photo","qty":"optional, for the sankalp"}]'::jsonb,
   '[{"q":"Does this puja guarantee pregnancy?","a":"No. It is a spiritual practice and cannot guarantee conception."},{"q":"Should we continue fertility treatment?","a":"Yes. Continue with the medical evaluation and treatment recommended by qualified clinicians."},{"q":"Do both partners need to be present?","a":"Not always. Both names can be included in the sankalp, and live participation can be arranged where available."},{"q":"Is Santan Gopal Puja automatically included?","a":"No. Some practitioners combine it, others perform a Baglamukhi-specific anushthan. Your package discloses this."},{"q":"Can it be online?","a":"Yes."},{"q":"Do we need a kundli?","a":"Only if the pandit is adding astrology-based graha remedies."},{"q":"What does the service actually offer?","a":"Prayer, hope, spiritual support and a family blessing — never a medical claim or a promised outcome."}]'::jsonb),

  ('Graha Shanti Puja', 'graha-shanti-baglamukhi-puja', 'moon', 110,
   'Grah Dosh Nivaran and Navgraha Shanti are commonly offered alongside Maa Baglamukhi worship at Nalkheda. If you are paying for a specific dosha remedy, the ritual should never be generic: the assigned pandit identifies whether the focus is Shani, Rahu-Ketu, Mangal, the full Navgraha or another graha. A typical package includes Ganesh puja, Navgraha avahan, graha mantra-japa, Maa Baglamukhi pujan and havan. A kundli review is encouraged before any personalised graha claim is made — a difficult phase in life is not by itself proof that you have a dosha, and you will not be told otherwise here. Choose this service for a kundli-identified graha dosha, a Rahu-Ketu, Shani or Mangal-related concern, multiple planetary concerns, or a general Navgraha shanti.',
   'For devotees who have been advised that one or more planetary influences may need shanti. Combines Baglamukhi protection with the appropriate graha or Navgraha worship.',
   '2.5-4 hours',
   'Ideally after a kundli review when the service is dosha-specific. The date is selected according to the relevant graha and the local Panchang.',
   'Live sankalp participation is possible; birth details can be shared in advance for a dosha-specific booking.',
   '[{"icon":"🌙","title":"Graha shanti prayer","detail":"Traditional worship for planetary pacification."},{"icon":"🛡️","title":"Baglamukhi protection","detail":"Combines graha remedies with a Devi protection-oriented prayer."},{"icon":"📿","title":"Personalised sankalp","detail":"Can be tailored to the specific graha identified in your chart."},{"icon":"🧘","title":"Mental steadiness","detail":"A structured spiritual response to an astrological concern."},{"icon":"🪔","title":"Obstacle pacification","detail":"Often chosen when repeated delays are associated with planetary periods."},{"icon":"🕉️","title":"Navgraha reverence","detail":"Honours the planetary deities according to Vedic-astrological tradition."}]'::jsonb,
   '[{"step":1,"title":"Kundli / Concern Review","detail":"The relevant graha is identified, or a general Navgraha service is agreed.","duration":""},{"step":2,"title":"Ganesh & Kalash Pujan","detail":"The opening worship.","duration":""},{"step":3,"title":"Navgraha / Specific Graha Avahan","detail":"The relevant grahas are invoked and worshipped.","duration":""},{"step":4,"title":"Baglamukhi Pujan & Mantra","detail":"Maa Baglamukhi is worshipped for protection and obstacle pacification.","duration":""},{"step":5,"title":"Graha Shanti Havan","detail":"Havan is performed with graha-appropriate and Baglamukhi samagri.","duration":""},{"step":6,"title":"Purnahuti & Daan Guidance","detail":"A closing prayer; any traditional daan is suggested by the pandit rather than fixed in advance.","duration":""}]'::jsonb,
   '[{"item":"Navgraha set / symbols","qty":"1 set"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Navdhanya / nine grains","qty":"1 set if Navgraha is included"},{"item":"Flowers","qty":"appropriate / available colours"},{"item":"Akshat, roli, sandal, moli","qty":"1 set"},{"item":"Ghee","qty":"500 ml approx."},{"item":"Havan samagri","qty":"1 pack"},{"item":"Graha-specific sesame/grains","qty":"as advised"},{"item":"Incense, camphor, lamps","qty":"1 set"},{"item":"Fruits / sweets","qty":"as required"},{"item":"Daan items","qty":"only as advised by the pandit"}]'::jsonb,
   '[{"q":"Do I need a kundli?","a":"For a specific dosha remedy, a kundli review is strongly recommended. A general Navgraha prayer can be performed without a personalised diagnosis."},{"q":"Is this the same as Navgraha Shanti Puja?","a":"It may include Navgraha Shanti, but the Baglamukhi version also adds Maa Baglamukhi worship. Your package states the exact scope."},{"q":"Can it include Rahu-Ketu or Shani remedies?","a":"Yes, if those are the identified concerns and the assigned pandit includes them."},{"q":"Can it be online?","a":"Yes."},{"q":"Is one muhurat suitable for every graha?","a":"No. Timing may vary by the graha, the chart and the local Panchang."},{"q":"Does a bad phase prove that I have graha dosha?","a":"No. Life difficulties alone are not proof of an astrological dosha."},{"q":"Are results guaranteed?","a":"No. This is a traditional spiritual and astrological practice."}]'::jsonb),

  ('Tantra Badha / Negative Energy Protection Puja', 'tantra-badha-negative-energy-protection-baglamukhi-puja', 'diya', 120,
   'This category is offered carefully, and it is worth saying why. Fear, anxiety, illness, financial loss or a relationship problem is not proof of black magic or tantra badha, and you will not be told that it is. This is an optional spiritual protection ritual for devotees who find meaning in the tradition, and practical or professional help for real-world problems is encouraged alongside it. The ritual includes Baglamukhi pujan, protective mantra-japa, havan and shanti prayers. Any advanced tantric method stays under a qualified acharya and never involves harm, coercion or dangerous substances. Choose this service for perceived negativity, a nazar-related spiritual concern, fear of harmful influence, an uneasy home or work environment, repeated unexplained spiritual worry, or a general protection sankalp.',
   'For devotees worried about perceived negative spiritual influence, fear, nazar-like disturbance or repeated unexplained uneasiness. Focused on protection, peace and grounding — without claiming that black magic has been proven.',
   '2-4 hours; an extended anushthan may take longer',
   'Consultation-based. The acharya chooses a suitable tithi and method — advanced tantric details should never be self-prescribed.',
   'Available after a consultation and a clear, non-harmful sankalp is agreed with the pandit.',
   '[{"icon":"🛡️","title":"Protection prayer","detail":"Maa Baglamukhi is invoked for spiritual protection and steadiness."},{"icon":"🪔","title":"Peace and grounding","detail":"A structured, calming devotional process."},{"icon":"🕊️","title":"Fear reduction","detail":"Supports devotees who feel spiritually unsettled, without validating unproven causes."},{"icon":"🏠","title":"Home and environment shanti","detail":"Can be offered with a prayer for a calmer environment."},{"icon":"🧘","title":"Obstacle pacification","detail":"Focused on reducing recurring disturbance and perceived negativity."},{"icon":"🙏","title":"Ethical spiritual guidance","detail":"A qualified pandit can steer you away from harmful or exploitative practices."}]'::jsonb,
   '[{"step":1,"title":"Private Concern Discussion","detail":"The pandit listens, without declaring that black magic is definitely present.","duration":""},{"step":2,"title":"Protection Sankalp & Shuddhi","detail":"A non-harmful protection and peace intention is taken.","duration":""},{"step":3,"title":"Baglamukhi Avahan","detail":"Maa Baglamukhi is worshipped with the standard yellow offerings.","duration":""},{"step":4,"title":"Protective Mantra Jaap","detail":"The acharya recites the appropriate traditional mantra.","duration":""},{"step":5,"title":"Protection Havan","detail":"Havan is performed with safe, prescribed samagri.","duration":""},{"step":6,"title":"Purnahuti & Shanti Guidance","detail":"A final prayer for peace and confidence, with practical next steps where they are needed.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Turmeric / yellow mustard","qty":"as advised"},{"item":"Yellow flowers","qty":"as required"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Samidha / wood","qty":"as required"},{"item":"Akshat, sandal, roli, moli","qty":"1 set"},{"item":"Incense, camphor, lamp","qty":"1 set"},{"item":"Salt/lemon/chilli or other folk items","qty":"only if the qualified pandit specifically uses them; not a default"},{"item":"Naivedya","qty":"as required"}]'::jsonb,
   '[{"q":"How do I know if I have tantra badha or black magic?","a":"We do not diagnose this. Many ordinary medical, psychological, financial or relationship problems can feel unexplained — please seek appropriate professional help where it is relevant."},{"q":"What is this puja for, then?","a":"It is a spiritual protection and peace ritual for devotees who wish to follow the Baglamukhi tradition."},{"q":"Can it harm another person?","a":"No. Only protection-oriented, non-harmful sankalps are accepted."},{"q":"Can it be performed online?","a":"Yes, once the pandit understands the concern and the sankalp is agreed."},{"q":"Are special ingredients always used?","a":"No. Methods differ by lineage. Advanced or unusual samagri should never be assumed or used on your own."},{"q":"Should I stop medical or mental-health treatment?","a":"No."},{"q":"Can the pandit guarantee that negativity will disappear?","a":"No. No spiritual outcome is guaranteed."}]'::jsonb),

  ('Sarva Badha Nivaran Puja', 'sarva-badha-nivaran-baglamukhi-puja', 'om', 130,
   'Sarva Badha Nivaran is the right starting point when the difficulty is broad rather than specific. Nalkheda practitioners use this name when a devotee reports recurring blocks across career, family, business or mental peace but has no single clear diagnosis or purpose. Rather than pushing you into Court Case, Graha Shanti or Tantra Badha, this service takes a general protection and obstacle-removal sankalp. The ritual includes sankalp, Ganesh puja, Maa Baglamukhi pujan, mantra-japa, havan and purnahuti. If the consultation reveals a more specific need, the pandit can recommend a suitable related service — with your approval before anything changes. Choose it for multiple recurring obstacles, an unclear source of difficulty, a general protection prayer, mixed family and work stress, repeated delays, or when you are simply unsure which Baglamukhi service fits.',
   'For devotees facing repeated obstacles in more than one area of life, and unsure which specialised service to choose. A broad Baglamukhi prayer for protection, clarity, peace and the removal of obstacles.',
   '2-4 hours',
   'A general auspicious Devi muhurat selected by the pandit — suitable when the concern is broad rather than one specific dosha.',
   'Live sankalp participation is possible, with the general concern discussed before the ritual is fixed.',
   '[{"icon":"🕉️","title":"Broad obstacle prayer","detail":"Suitable when problems span more than one area of life."},{"icon":"🛡️","title":"Protection","detail":"A traditional Baglamukhi protection sankalp."},{"icon":"🧭","title":"Clarity","detail":"Allows a general spiritual reset without inventing a specific dosha."},{"icon":"🧘","title":"Peace and steadiness","detail":"Supports a calmer response to repeated setbacks."},{"icon":"🪔","title":"Flexible ritual","detail":"The pandit can adapt the mantra and samagri after understanding your concern."},{"icon":"🤝","title":"Gateway to specific guidance","detail":"If a clear issue emerges, you can be referred to a more specialised service."}]'::jsonb,
   '[{"step":1,"title":"General Concern & Sankalp","detail":"You briefly explain the main areas of repeated difficulty.","duration":""},{"step":2,"title":"Shuddhi, Ganesh & Kalash Pujan","detail":"Opening purification and auspicious worship.","duration":""},{"step":3,"title":"Maa Baglamukhi Pujan","detail":"The Devi is invoked with the yellow offerings.","duration":""},{"step":4,"title":"Sarva Badha Mantra Jaap","detail":"Baglamukhi mantra-japa for broad protection and obstacle pacification.","duration":""},{"step":5,"title":"Sarva Badha Nivaran Havan","detail":"A standard havan with safe, prescribed samagri.","duration":""},{"step":6,"title":"Purnahuti, Aarti & Guidance","detail":"A closing prayer; the pandit suggests a specific follow-up only if one is genuinely needed.","duration":""}]'::jsonb,
   '[{"item":"Yellow cloth","qty":"1"},{"item":"Baglamukhi image/yantra","qty":"1"},{"item":"Kalash & coconut","qty":"1 set"},{"item":"Yellow flowers","qty":"as required"},{"item":"Turmeric / yellow mustard","qty":"as advised"},{"item":"Akshat / rice","qty":"1 bowl"},{"item":"Ghee","qty":"250-500 ml"},{"item":"Havan samagri","qty":"1 pack"},{"item":"Mango wood / samidha","qty":"as required"},{"item":"Roli, moli, sandal, supari","qty":"1 set"},{"item":"Incense, camphor, lamp","qty":"1 set"},{"item":"Fruits / sweets","qty":"as required"}]'::jsonb,
   '[{"q":"When should I choose Sarva Badha Nivaran instead of another service?","a":"Choose it when you face several recurring obstacles and have no one clear issue such as a court case or a specific graha dosha."},{"q":"Is this a general Baglamukhi Havan?","a":"It is closely related, but the sankalp is specifically framed around broad obstacle removal and protection."},{"q":"Do I need a kundli?","a":"No, not for a general service. A kundli is only needed if a graha-specific remedy is later considered."},{"q":"Can it be online?","a":"Yes."},{"q":"Does it include Shatru Stambhan?","a":"Not automatically. It is a broad protection service; any specialised element is disclosed if it is added."},{"q":"Can the pandit change the service after the consultation?","a":"The pandit may recommend a more suitable option, but you approve any change in scope or price before it happens."},{"q":"Are results guaranteed?","a":"No. It is a devotional practice, and practical action should continue alongside it."}]'::jsonb)
)
INSERT INTO public.services
  (category_id, name, slug, icon_name, display_order,
   description, short_description, estimated_duration,
   recommended_muhurat, online_note,
   benefits, process, samagri_list, faqs,
   is_online_available, is_popular, is_active)
SELECT (SELECT id FROM cat),
       i.name, i.slug, i.icon_name, i.display_order,
       i.description, i.short_description, i.estimated_duration,
       i.recommended_muhurat, i.online_note,
       i.benefits, i.process, i.samagri_list, i.faqs,
       TRUE,   -- every one of the thirteen is offered with remote sankalp
       FALSE,  -- "popular" is an admin's editorial call, not a seed's
       FALSE   -- draft until an admin adds the image and activates it
  FROM incoming i
ON CONFLICT (slug) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Self-check
-- ----------------------------------------------------------------------------
DO $verify$
DECLARE
  found INT;
BEGIN
  SELECT COUNT(*) INTO found
    FROM public.services s
    JOIN public.service_categories sc ON sc.id = s.category_id
   WHERE s.slug IN ('court-case-vijay-baglamukhi-puja',
                    'shatru-stambhan-baglamukhi-puja',
                    'shatru-nash-protection-baglamukhi-puja',
                    'rajneeti-vijay-baglamukhi-puja',
                    'business-growth-baglamukhi-puja',
                    'lakshmi-dhan-prapti-baglamukhi-puja',
                    'career-job-success-baglamukhi-puja',
                    'rog-nashak-baglamukhi-puja',
                    'vivah-badha-nivaran-baglamukhi-puja',
                    'santan-prapti-baglamukhi-puja',
                    'graha-shanti-baglamukhi-puja',
                    'tantra-badha-negative-energy-protection-baglamukhi-puja',
                    'sarva-badha-nivaran-baglamukhi-puja');

  IF found <> 13 THEN
    RAISE EXCEPTION 'Migration 0013 incomplete — expected 13 Baglamukhi sub-services, found %', found;
  END IF;
END
$verify$;
